### Load in NumPy (remember to pip install numpy first)

In [35]:
import numpy as np

In [36]:
# Check numpy version
np.__version__

'1.20.3'

In [37]:
# Check all functions in numpy
np.__dir__()

['size',
 'polydiv',
 'sometrue',
 'longlong',
 'True_',
 'ptp',
 'interp',
 'moveaxis',
 '__name__',
 'swapaxes',
 '_pytesttester',
 'bincount',
 'exp2',
 'log',
 'logaddexp2',
 '__package__',
 'sqrt',
 'real_if_close',
 'zeros',
 'isneginf',
 'polyval',
 'WRAP',
 'maximum',
 'meshgrid',
 'nanmedian',
 'void0',
 'unicode_',
 'format_float_scientific',
 'isnat',
 'sinh',
 'cumsum',
 'AxisError',
 'memmap',
 'ubyte',
 'fill_diagonal',
 'eye',
 'zeros_like',
 'compat',
 'bitwise_not',
 'record',
 'void',
 'conjugate',
 'ravel',
 'fastCopyAndTranspose',
 'ScalarType',
 'bartlett',
 'tril_indices_from',
 'fabs',
 'ALLOW_THREADS',
 'float16',
 'clongfloat',
 'roll',
 'isrealobj',
 'ndenumerate',
 'average',
 'log1p',
 'info',
 'signbit',
 'isposinf',
 'fmod',
 'get_printoptions',
 'amax',
 'blackman',
 'test',
 'indices',
 'left_shift',
 '__builtins__',
 'busday_count',
 'modf',
 'ascontiguousarray',
 'uint8',
 'searchsorted',
 'reciprocal',
 'histogram_bin_edges',
 'alltrue',
 'add_newdoc_

### The Basics

In [38]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [39]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [40]:
# Get Dimension
b.ndim

2

In [41]:
# Get Shape
b.shape

(2, 3)

In [42]:
# Get Type
a.dtype

dtype('int32')

In [43]:
# Get Size
a.itemsize

4

In [44]:
# Get total size
a.nbytes

12

In [45]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [46]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [47]:
# Get a specific element [r, c]
a[1, 5]

13

In [48]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [50]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [51]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [52]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
# Get specific element (work outside in)
b[0,1,1]

4

In [60]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [61]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Copy vs View

In [95]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [98]:
arr = np.array([1, 2, 3, 4, 5])
y = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


### Iterating

In [107]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

for x in arr:
      for y in x:
        print(y,end =" ")

[1 2 3]
[4 5 6]
1 2 3 4 5 6 

### Splitting Array

In [108]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [115]:
#For 2-D arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [118]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Searching and Sorting

In [121]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)

y= np.sort(arr)
print(y)

(array([3, 5, 6], dtype=int64),)
[1 2 3 4 4 4 5]


### Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3))

In [63]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [64]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [65]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [74]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.87496751, 0.69752043],
       [0.24959004, 0.32485191],
       [0.93029554, 0.289443  ],
       [0.86295909, 0.3829033 ]])

In [75]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 0,  3, -3],
       [-2, -4,  1],
       [ 2,  2,  4]])

In [76]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

### Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
a + b

In [ ]:
a ** 2

In [ ]:
# Take the sin
np.cos(a)



In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [81]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [82]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [83]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
np.min(stats)

1

In [85]:
np.max(stats, axis=1)

array([3, 6])

In [87]:
np.sum(stats, axis=1)

array([ 6, 15])

### Reorganizing Arrays

In [91]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(8,1)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [92]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

### Miscellaneous
##### Load Data from File

In [94]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[11  1  2  3 22 51]


##### Boolean Masking and Advanced Indexing

In [ ]:
(~((filedata > 50) & (filedata < 100)))